# ---- API image (slim) ----
FROM python:3.11-slim

WORKDIR /app

# System deps for API (minimal)
RUN apt-get update && apt-get install -y \
    libmagic1 \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

COPY ./src .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
